package com.ordering.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCombo<M extends BaseCombo<M>> extends Model<M> implements IBean {

	public void setComboId(java.lang.Integer comboId) {
		set("combo_id", comboId);
	}

	public java.lang.Integer getComboId() {
		return get("combo_id");
	}

	public void setComboName(java.lang.String comboName) {
		set("combo_name", comboName);
	}

	public java.lang.String getComboName() {
		return get("combo_name");
	}

	public void setDishes(java.lang.Integer dishes) {
		set("dishes", dishes);
	}

	public java.lang.Integer getDishes() {
		return get("dishes");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}

	public java.lang.Integer getOrderNum() {
		return get("order_num");
	}

	public void setBookings(java.lang.Integer bookings) {
		set("bookings", bookings);
	}

	public java.lang.Integer getBookings() {
		return get("bookings");
	}

}
