package com.ordering.common.model;

import com.ordering.common.model.base.BaseCombo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Combo extends BaseCombo<Combo> {
	public static final Combo dao = new Combo().dao();
}
