/**
 * default_1468734074112
 * 专注短信行业8年运营与�?术积累，自主研发系统，后台稳健�?�结合三大运营商优质通道，支持自定义签名及内容�??5秒极速�?�达。支持最新移动�?�电信�?�联通虚拟号段�??
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package api;

import wxlink.ApiCallback;
import wxlink.ApiClient;
import wxlink.ApiException;
import wxlink.ApiResponse;
import wxlink.Configuration;
import wxlink.Pair;
import wxlink.ProgressRequestBody;
import wxlink.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient apiClient;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for dxjk */
    private com.squareup.okhttp.Call dxjkCall(String mobile, String content, String appkey, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // verify the required parameter 'mobile' is set
        if (mobile == null) {
            throw new ApiException("Missing the required parameter 'mobile' when calling dxjk(Async)");
        }
        
        // verify the required parameter 'content' is set
        if (content == null) {
            throw new ApiException("Missing the required parameter 'content' when calling dxjk(Async)");
        }
        
        // verify the required parameter 'appkey' is set
        if (appkey == null) {
            throw new ApiException("Missing the required parameter 'appkey' when calling dxjk(Async)");
        }
        

        // create path and map variables
        String localVarPath = "/chuangxin/dxjk".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (mobile != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "mobile", mobile));
        if (content != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "content", content));
        if (appkey != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "appkey", appkey));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "text/plain"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * 标准化SDK�?发包（短信接口）适应Basic、C、Java等多种主流开发语�?，�?�应Windows、Linux、Unix等运行环境，彻底解决各个合作伙伴不同�?发语�?及开发环境的�?求�??
     * 标准化SDK�?发包（短信接口）适应Basic、C、Java等多种主流开发语�?，�?�应Windows、Linux、Unix等运行环境，彻底解决各个合作伙伴不同�?发语�?及开发环境的�?求�??
     * @param mobile 发�?�目标号码，多个号码之间用半角英文标点�?�号隔开 (required)
     * @param content 短信内容，需要UTF-8编码 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public String dxjk(String mobile, String content, String appkey) throws ApiException {
        ApiResponse<String> resp = dxjkWithHttpInfo(mobile, content, appkey);
        return resp.getData();
    }

    /**
     * 标准化SDK�?发包（短信接口）适应Basic、C、Java等多种主流开发语�?，�?�应Windows、Linux、Unix等运行环境，彻底解决各个合作伙伴不同�?发语�?及开发环境的�?求�??
     * 标准化SDK�?发包（短信接口）适应Basic、C、Java等多种主流开发语�?，�?�应Windows、Linux、Unix等运行环境，彻底解决各个合作伙伴不同�?发语�?及开发环境的�?求�??
     * @param mobile 发�?�目标号码，多个号码之间用半角英文标点�?�号隔开 (required)
     * @param content 短信内容，需要UTF-8编码 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<String> dxjkWithHttpInfo(String mobile, String content, String appkey) throws ApiException {
        com.squareup.okhttp.Call call = dxjkCall(mobile, content, appkey, null, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 标准化SDK�?发包（短信接口）适应Basic、C、Java等多种主流开发语�?，�?�应Windows、Linux、Unix等运行环境，彻底解决各个合作伙伴不同�?发语�?及开发环境的�?求�?? (asynchronously)
     * 标准化SDK�?发包（短信接口）适应Basic、C、Java等多种主流开发语�?，�?�应Windows、Linux、Unix等运行环境，彻底解决各个合作伙伴不同�?发语�?及开发环境的�?求�??
     * @param mobile 发�?�目标号码，多个号码之间用半角英文标点�?�号隔开 (required)
     * @param content 短信内容，需要UTF-8编码 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call dxjkAsync(String mobile, String content, String appkey, final ApiCallback<String> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = dxjkCall(mobile, content, appkey, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
