package com.ordering.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		
		arp.addMapping("cart", "user_id", Cart.class);
		arp.addMapping("combo", "combo_id", Combo.class);
		arp.addMapping("menu", "dishes_id", Menu.class);
		arp.addMapping("orders", "order_id", Orders.class);
		arp.addMapping("stock", "stock_id", Stock.class);
		arp.addMapping("user", "user_id", User.class);
	}
}

