package com.ordering.common.model;

import java.util.List;

import com.ordering.common.model.base.BaseCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cart extends BaseCart<Cart> {

}
