package com.ordering.common.model;

import com.ordering.common.model.base.BaseComboDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ComboDetail extends BaseComboDetail<ComboDetail> {
	public static final ComboDetail dao = new ComboDetail().dao();
}
