package com.ordering.common.model;

import com.ordering.common.model.base.BaseManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manager extends BaseManager<Manager> {
	
}
