package com.ordering.common.model;

import com.ordering.common.model.base.BaseOrdersDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrdersDetail extends BaseOrdersDetail<OrdersDetail> {
	public static final OrdersDetail dao = new OrdersDetail().dao();
}
