package com.ordering.common.model;

import com.ordering.common.model.base.BaseStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stock extends BaseStock<Stock> {
	public static final Stock dao = new Stock().dao();
}
