package com.ordering.common.model;

import java.util.List;


import com.ordering.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	
}
 