/**
 * default_1468734074112
 * 专注短信行业8年运营与技术积累，自主研发系统，后台稳健。结合三大运营商优质通道，支持自定义签名及内容。5秒极速送达。支持最新移动、电信、联通虚拟号段。
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package wxlink.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
