package com.ordering.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setDishesId(java.lang.Integer dishesId) {
		set("dishes_id", dishesId);
	}

	public java.lang.Integer getDishesId() {
		return get("dishes_id");
	}

	public void setDishesName(java.lang.String dishesName) {
		set("dishes_name", dishesName);
	}

	public java.lang.String getDishesName() {
		return get("dishes_name");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setBookings(java.lang.Integer bookings) {
		set("bookings", bookings);
	}

	public java.lang.Integer getBookings() {
		return get("bookings");
	}

}
